lang: pt    
author: "Steven Dutt-Ross"

execute:
  echo: false         # Hide code by default
  warning: false      # Hide warnings by default
  message: false      # Hide messages by default
  
format:
  html: 
    css: styles.css
    code-fold: true   # Enable code folding
    toc: true         # Include table of contents
    toc-depth: 3
    toc-location: left
    toc-title: "Tópicos"
